'''
ROSALIND Task #3

Reverse complement a strand of DNA. Starting to get a little bit more elaborate
but not by much. A strand of DNA is always double-stranded where individual
nucleotides are hydrogen-bonded to their reverse complement.
                  Adenine <-> Thymine (2 H-bonds)
                  Cytosine <-> Guanine (3 H-bonds)
'''

def revComp(dnaString):
  basePairs = { "A" : "T", "T" : "A", "C" : "G", "G" : "C"}
  revString = dnaString[::-1]
  revCompList = []
  for nt in revString:
    revCompList.append(basePairs[nt])
  revCompString = ''.join(revCompList)
  return revCompString

def main():
  dna = 'GTCTAAATGAAGGGAGTAGCTCCCACTGGCTGCGGGATCCGGTCGAAGGTTCGTGTCAATGCAGGCACGTGCCGTAATGACTCAGCGCTTAATAAAGAATACTAGGACGCTGTCTATCGTCGCCGACAGGTTCAGTTCAAGGGATATTTAGCTGGATGGGAACCTACGGCCGCACTAGAAAGATAGCCTATCTTTTGGCCCGTTGCTTGCTACAGCAGACACAACACGCGCCCGTCTTCGTTTCGGCGTGGGACAACGCCGCGCTTCAGCTTACAGTATGCCATAATCAAAAGTAAGCCTACGCAATTCCGAGAGAAAGCTCATTTATACGCGTACCACGAGACATTAGACTATATTGTTGACTGAGGCCAACCCTTGTCCGCCGAAAATTAAGGAGAGCTGTATGGAATCAGGCTCAAGCTTGAGCGCAAGGCACTCAGGGCCATTAAAATCATGCATCAGTGTGCTCCCTTGAAATACGGTATCAGGACCTACTGTAGACGTCCGCAAAGCCGATTGTCACTCTCATTGCAGCCGGCAAAAGTCACAATTCAAAGACCCAACCCGGGGGGAGTGCATTTAACGATCATACTATGGCTGCGGGTGAAGCCACCCGCGGCATTCGATGGGCAGATTGTGGATTGCGAAATCATTCGGTCCAAATACCTTCTTCCACGTATGCTTTAGTGTTTTACCACTGAGCCTCGTTATCAACGCCGTCCTGGCCGCCGTGATGATCACTATGGAGACGGATGACCGCTATGTCTCCCACATCCCCAGTACGGTACGTCACTCAGTCGTTAGGTGGGTCTACGGGGACTAAGAACAAGATGCATCGGCCATGCTGACGCCATGCTTGGCAAGTCCTGGTGTTGTCCGGCCA'
  revCompString = revComp(dna)
  print "DNA: ", dna
  print "Reverse Complement: ", revCompString

main()
